version: '3.8'

services:
  app:
    image: placeholder-will-be-replaced-by-pipeline
    container_name: digimall-admin
    ports:
      - '4300:4300'
    env_file:
      - .env.admin
    environment:
      - NODE_ENV=production
      - PORT=4300
      - SETUP_COMPLETED=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4300/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs:/app/logs

networks:
  default:
    name: digimall-admin-prod-network