name: 'Send Notification to Zoho Cliq'
description: 'A custom GitHub Action to send notifications to Zoho Cliq'

inputs:
  CLIQ_URL:
    description: 'The Zoho cliq API URL.'
    required: true
  MESSAGE:
    description: 'The message to send to cliq channel.'
    required: true


runs:
  using: 'composite'
  steps:
    - run: |
        cd ./.github/actions/notify-cliq
        chmod +x entrypoint.sh
        ./entrypoint.sh
      shell: bash
      env:
        CLIQ_URL: ${{ inputs.CLIQ_URL }}
        MESSAGE: ${{ inputs.MESSAGE }}